webhook:
  enabled: true
  port: 3001
  use-tls: false
  certificates:
      - name: certificate-1
        certfile: dependencies/cert/localhost.crt
        keyfile: dependencies/cert/localhost.key

amqp:
  enabled: false
  address: amqp://localhost
  queue: notification
